#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export EDITOR='vim'
export VISUAL='gvim'

# auto-correction is driving me nuts
unsetopt correct

export PYTHONPATH=/Library/Python/2.7/site-packages:/usr/local/lib/python2.7/site-packages:$HOME/Work/:$HOME/Work/tools/python

export NDK_ROOT=$HOME/Work/android/android-ndk-r10
export NDK_TOOLCHAIN=$NDK_ROOT/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi

export ANDROID_SDK_ROOT=$HOME/Work/android/adt-bundle-mac-x86_64-20140702/sdk
export ANDROID_PLATFORM_TOOLS=$ANDROID_SDK_ROOT/platform-tools

alias xgcc=$NDK_TOOLCHAIN-gcc
alias xld=$NDK_TOOLCHAIN-ld
alias xar=$NDK_TOOLCHAIN-ar
alias xas=$NDK_TOOLCHAIN-as
alias xelfedit=$NDK_TOOLCHAIN-xelfedit
alias xgdb=$NDK_TOOLCHAIN-gdb
alias xnm=$NDK_TOOLCHAIN-nm
alias xobjcopy=$NDK_TOOLCHAIN-objcopy
alias xobjdump=$NDK_TOOLCHAIN-objdump
alias xrunlib=$NDK_TOOLCHAIN-runlib
alias xreadelf=$NDK_TOOLCHAIN-readelf
alias xsize=$NDK_TOOLCHAIN-size
alias xstrings=$NDK_TOOLCHAIN-strings
alias xstrip=$NDK_TOOLCHAIN-strip

if [[ -s "${ZDOTDIR:-$HOME}/.secrets" ]]; then
  source "${ZDOTDIR:-$HOME}/.secrets"
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zaliases.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zaliases.zsh"
fi

export PATH=$PATH:$ANDROID_PLATFORM_TOOLS:$HOME/bin

export MANPAGER="col -b | vim -c 'set ft=man nomod' -"
